import pandas as pd

import numpy as np

import sklearn 

# KNN 분류모델을 위한 패키지 임포트 
from sklearn.neighbors import KNeighborsClassifier 

# 학습 및 테스트 데이터셋 분리를 위한 패키지 임포트 
from sklearn.model_selection import train_test_split 




from google.colab import drive
drive.mount('/content/drive')




df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/iris.csv")






x = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df['species']



x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=11)




print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)



knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train, y_train)







pred = knn.predict(x_test)




from sklearn.metrics import confusion_matrix
mat = confusion_matrix(y_test, pred)
print(mat)



from sklearn.metrics import classification_report
rpt = classification_report(y_test, pred)
print(rpt)
